src/Entity/Driver.php
<?php

namespace App\Entity;

use App\Repository\DriverRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=DriverRepository::class)
 */
class Driver
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"user"})
     */
    private $id;
    /**
     * @Assert\NotBlank
     * @Assert\NotNull
     * @Assert\Length(min=5)
     * @ORM\Column(type="string", length=255)
     * @Groups({"user"})
     */
    private $phone;

    /**
     * @Assert\NotBlank
     * @Assert\NotNull
     * @ORM\Column(type="text")
     * @Groups({"user"})
     */
    private $address;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups({"user"})
     */
    private $addional_address;

    /**
     * 
     * @ORM\OneToOne(targetEntity="App\Entity\City")
     * @Groups({"user"})
     */
    private $city;

     /**
     * @ORM\OneToMany(targetEntity="App\Entity\File", mappedBy="driver",cascade={"persist","remove"})
     * @Groups({"user"})
     */
    private $files;

      /**
     * @ORM\OneToMany(targetEntity="App\Entity\Car", mappedBy="driver", orphanRemoval=true,cascade={"persist"})
     * @Groups({"user"})
     */
    private $cars;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", orphanRemoval=true,cascade={"persist","remove"})
     * @Groups({"user"})
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Choice", mappedBy="driver", cascade={"persist", "remove"})
     */
    private $choices;

    public function __construct()
    {
        $this->files = new ArrayCollection();
        $this->cars = new ArrayCollection();
        $this->choices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddressName(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getAddionalAddress(): ?string
    {
        return $this->addional_address;
    }

    public function setAddionalAddress(?string $addional_address): self
    {
        $this->addional_address = $addional_address;

        return $this;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    /**
     * @return Collection|File[]
     */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(File $file): self
    {
        if (!$this->files->contains($file)) {
            $this->files[] = $file;
            $file->setDriver($this);
        }

        return $this;
    }

    public function removeFile(File $file): self
    {
        if ($this->files->removeElement($file)) {
            // set the owning side to null (unless already changed)
            if ($file->getDriver() === $this) {
                $file->setDriver(null);
            }
        }

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection|Car[]
     */
    public function getCars(): Collection
    {
        return $this->cars;
    }

    public function addCar(Car $car): self
    {
        if (!$this->cars->contains($car)) {
            $this->cars[] = $car;
            $car->setDriver($this);
        }

        return $this;
    }

    public function removeCar(Car $car): self
    {
        if ($this->cars->removeElement($car)) {
            // set the owning side to null (unless already changed)
            if ($car->getDriver() === $this) {
                $car->setDriver(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        $this->user->setRoles(['ROLE_DIRVER']);
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;
        $this->user->setRoles(['ROLE_DIRVER']);
        return $this;
    }

    /**
     * @return Collection|Choice[]
     */
    public function getChoices(): Collection
    {
        return $this->choices;
    }

    public function addChoice(Choice $choice): self
    {
        if (!$this->choices->contains($choice)) {
            $this->choices[] = $choice;
            $choice->setDriver($this);
        }

        return $this;
    }

    public function removeChoice(Choice $choice): self
    {
        if ($this->choices->removeElement($choice)) {
            // set the owning side to null (unless already changed)
            if ($choice->getDriver() === $this) {
                $choice->setDriver(null);
            }
        }

        return $this;
    }

}

src/Controller/DriverController.php
<?php

namespace App\Controller;

use App\Entity\Driver;
use App\Form\DriverType;
use App\Repository\DriverRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use SymfonyCasts\Bundle\VerifyEmail\VerifyEmailHelperInterface;

#[Route('api/drivers')]
class DriverController extends AbstractProAndDriverController
{
    protected $driverRepository;
    protected $serializer;
    protected $entityManager;
    protected $verifyEmailHelper;
    protected $mailer;

    public function __construct(
        DriverRepository $driverRepository,
        EntityManagerInterface $entityManager,
        SerializerInterface $serializer,
        ValidatorInterface $validator,
        UserPasswordEncoderInterface $passwordEncoder,
        VerifyEmailHelperInterface $helper, 
        MailerInterface $mailer
    ) {
        $this->driverRepository = $driverRepository;
        $this->serializer = $serializer;
        $this->entityManager = $entityManager;
        $this->verifyEmailHelper = $helper;
        $this->mailer = $mailer;
        parent::__construct($validator,$passwordEncoder);
    }
    
    #[Route('/', name: 'driver_list', methods: ['GET'])]
    public function list(DriverRepository $driverRepository): Response
    {
        $drivers = $driverRepository->findAll();

        return $this->json($drivers, 200, [], $this->userGroups);
    }

    #[Route('/', name: 'driver_new', methods: ['POST'])]
    public function new(Request $request): Response
    {
        $driver = new Driver;
        $driver = $this->getRequestDataIntoObject($driver);        
        $errors = $this->getProfessionalOrDriverErrors($driver);
        if (count($errors) > 0) {
            return $this->json($errors, JsonResponse::HTTP_BAD_REQUEST);
        }
        
        $this->encodeProfessionalOrDriverPassword($driver);
        
        $this->entityManager->persist($driver);
        $this->entityManager->flush();
        $this->SendEmail($driver);
        return $this->json($driver, 201, [], $this->userGroups);
    }

    #[Route('/{id}', name: 'driver_show', methods: ['GET'])]
    public function show(Driver $driver): JsonResponse
    {
        return $this->json($driver, 201, [], $this->userGroups);
    }

    #[Route('/{id}', name: 'driver_edit', methods: ['POST'])]
    public function edit(Request $request, Driver $driver): Response
    {
        $form = $this->createForm(DriverType::class, $driver);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('driver_index');
        }

        return $this->render('driver/edit.html.twig', [
            'driver' => $driver,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'driver_delete', methods: ['DELETE'])]
    public function delete(Request $request, Driver $driver): Response
    {
        if ($this->isCsrfTokenValid('delete'.$driver->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($driver);
            $entityManager->flush();
        }

        return $this->redirectToRoute('driver_index');
    }
}

templates/driver/_delete_form.html.twig
<form method="post" action="{{ path('driver_delete', {'id': driver.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ driver.id) }}">
    <button class="btn">Delete</button>
</form>

templates/driver/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/driver/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Driver{% endblock %}

{% block body %}
    <h1>Edit Driver</h1>

    {{ include('driver/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('driver_index') }}">back to list</a>

    {{ include('driver/_delete_form.html.twig') }}
{% endblock %}

templates/driver/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Driver index{% endblock %}

{% block body %}
    <h1>Driver index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Lastname</th>
                <th>Firstname</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Addional_address</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for driver in drivers %}
            <tr>
                <td>{{ driver.id }}</td>
                <td>{{ driver.lastname }}</td>
                <td>{{ driver.firstname }}</td>
                <td>{{ driver.email }}</td>
                <td>{{ driver.phone }}</td>
                <td>{{ driver.address }}</td>
                <td>{{ driver.addionalAddress }}</td>
                <td>
                    <a href="{{ path('driver_show', {'id': driver.id}) }}">show</a>
                    <a href="{{ path('driver_edit', {'id': driver.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('driver_new') }}">Create new</a>
{% endblock %}

templates/driver/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Driver{% endblock %}

{% block body %}
    <h1>Create new Driver</h1>

    {{ include('driver/_form.html.twig') }}

    <a href="{{ path('driver_index') }}">back to list</a>
{% endblock %}

templates/driver/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Driver{% endblock %}

{% block body %}
    <h1>Driver</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ driver.id }}</td>
            </tr>
            <tr>
                <th>Lastname</th>
                <td>{{ driver.lastname }}</td>
            </tr>
            <tr>
                <th>Firstname</th>
                <td>{{ driver.firstname }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ driver.email }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ driver.phone }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ driver.address }}</td>
            </tr>
            <tr>
                <th>Addional_address</th>
                <td>{{ driver.addionalAddress }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('driver_index') }}">back to list</a>

    <a href="{{ path('driver_edit', {'id': driver.id}) }}">edit</a>

    {{ include('driver/_delete_form.html.twig') }}
{% endblock %}